/*
 * Copyright (c) 2024 Mike Cowan.
 *
 * This source code is subject to the terms of the GNU General Public
 * License, version 3. If a copy of the GPL was not distributed with this
 * file, You can obtain one at: https://www.gnu.org/licenses/gpl-3.0.txt
 */

package io.blt.gregbot.ui.forms;

import java.awt.*;
import java.awt.event.KeyEvent;

import static io.blt.gregbot.ui.utils.AwtUtils.scaleDimension;
import static io.blt.gregbot.ui.utils.AwtUtils.screenSize;
import static io.blt.gregbot.ui.utils.SwingUtils.scaleIcon;
import static java.util.Objects.requireNonNull;

import javax.swing.*;

public class SplashScreen extends JDialog {

    private JPanel contentPane;
    private JLabel image;

    public SplashScreen(String path, long timeoutInMillis) {
        setContentPane(contentPane);

        setModalityType(ModalityType.APPLICATION_MODAL);
        setUndecorated(true);

        var desiredWidth = scaleDimension(screenSize(), 0.3).getWidth();
        var splash = splashClosestToWidth(path, desiredWidth);
        var scale = desiredWidth / splash.getIconWidth();

        image.setIcon(scaleIcon(splash, scale));

        pack();

        setLocationRelativeTo(null);

        contentPane.registerKeyboardAction(e -> dispose(),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW);

        new Thread(() -> {
            try {
                Thread.sleep(timeoutInMillis);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            dispose();
        }).start();
    }

    private ImageIcon splashClosestToWidth(String path, double width) {
        var resourceName = "2048.png";

        if (width <= 512) {
            resourceName = "512.png";
        } else if (width <= 1024) {
            resourceName = "1024.png";
        }

        return new ImageIcon(requireNonNull(SplashScreen.class.getResource(path + "/" + resourceName)));
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        image = new JLabel();
        image.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(image, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
