/*
 * Copyright (c) 2024 Mike Cowan.
 *
 * This source code is subject to the terms of the GNU General Public
 * License, version 3. If a copy of the GPL was not distributed with this
 * file, You can obtain one at: https://www.gnu.org/licenses/gpl-3.0.txt
 */

package io.blt.gregbot.ui.panels;

import com.formdev.flatlaf.fonts.jetbrains_mono.FlatJetBrainsMonoFont;
import io.blt.gregbot.ApplicationResources.ToolIcon;
import io.blt.gregbot.ui.components.LogbackPane;

import static io.blt.gregbot.ApplicationResources.toolIcon;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.TitledBorder;

public class LogPanel extends JPanel {

    private JPanel contentPane;
    private JScrollPane scrollPane;
    private LogbackPane logbackPane;
    private JToggleButton lineWrapButton;
    private JToggleButton snapToBottomButton;
    private JButton clearAllButton;
    private JToolBar toolbar;

    public LogPanel() {
        logbackPane.setFont(new Font(FlatJetBrainsMonoFont.FAMILY, Font.PLAIN, 13));

        lineWrapButton.setIcon(toolIcon(ToolIcon.WRAP));
        snapToBottomButton.setIcon(toolIcon(ToolIcon.ALIGN_BOTTOM));
        clearAllButton.setIcon(toolIcon(ToolIcon.TRASH));

        lineWrapButton.addItemListener(l -> logbackPane.toggleLineWrap());
        snapToBottomButton.addItemListener(l -> logbackPane.toggleAutoCaretToBottom());
        clearAllButton.addActionListener(l -> logbackPane.setText(null));

        lineWrapButton.setSelected(true);
        snapToBottomButton.setSelected(true);
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        scrollPane = new JScrollPane();
        contentPane.add(scrollPane, BorderLayout.CENTER);
        scrollPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null,
                TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        logbackPane = new LogbackPane();
        scrollPane.setViewportView(logbackPane);
        toolbar = new JToolBar();
        toolbar.setOrientation(1);
        contentPane.add(toolbar, BorderLayout.WEST);
        lineWrapButton = new JToggleButton();
        lineWrapButton.setText("");
        lineWrapButton.setToolTipText("Snap to Bottom");
        toolbar.add(lineWrapButton);
        snapToBottomButton = new JToggleButton();
        snapToBottomButton.setText("");
        snapToBottomButton.setToolTipText("Snap to Bottom");
        toolbar.add(snapToBottomButton);
        clearAllButton = new JButton();
        clearAllButton.setText("");
        clearAllButton.setToolTipText("Clear All");
        toolbar.add(clearAllButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
